#
#  SnowControl configuration
#  Last updated with version: ${project.version}
#
#  blocks can be listed as ID's or their names, 
#  but names must be exactly as seen here: 
#  http://jd.bukkit.org/apidocs/org/bukkit/Material.html
###

SnowFall: #this is only in biomes where snow falls naturally
  CheckEvery: 10 #number in seconds
  MaxChunksPerWorldAndCheck: 441 #max number of chunks to check per world every check
  AccumulationEnabled: true
  AccumulationChance: 1 #percent 0-100
  MaxAccumulationDefault: 7 # number of 'layers' of snow
  MaxAccumulationOverride: # Must match marerial name exactly
    LEAVES: 3
  MeltingEnabled: true
  MeltingChance: 0.5 #percent 0-100
  MeltDownCompletely: false #If true, snow could disappear during the day
  MinLightLevelToMelt: 11
  ChanceToFallThrough: 80 #percent 0-100
  CanFallThrough: #Air is always assumed
    - LEAVES
  CanReplace: #Air is always assumed
    -
  CanAccumulateOn:
    - BEDROCK
    - BRICK
    - CACTUS
    - CLAY
    - CLAY_BRICK
    - DIAMOND
    - DIAMOND_BLOCK
    - DIAMOND_ORE
    - DIRT
    - EMERALD
    - EMERALD_BLOCK
    - EMERALD_ORE
    - ENDER_STONE
    - GOLD_BLOCK
    - GOLD_ORE
    - GRASS
    - HUGE_MUSHROOM_1
    - HUGE_MUSHROOM_2
    - IRON_BLOCK
    - IRON_ORE
    - LAPIS_BLOCK
    - LAPIS_ORE
    - LEAVES
    - LOG
    - MELON_BLOCK
    - MOSSY_COBBLESTONE
    - NETHER_BRICK
    - NETHERRACK
    - OBSIDIAN
    - PUMPKIN
    - SAND
    - SANDSTONE
    - SMOOTH_BRICK
    - SOIL
    - STONE
    - WOOD
    - WOOL